name: 'Hello composite action'
description: 'This runs a composite action'
inputs:
  who-to-greet:
    description: 'The person you want to greet'
    required: true
    default: 'World'
  
runs:
  using: composite
  steps:
  - name: Set  greeting
    run: echo 'Hello ${{inputs.who-to-greet}}'
    shell: bash
  - name: Give you my favorite number
    run: echo 'My favorite number is ⓫.'
    shell: bash
  - name: Favorite Pet
    run: echo 'I love dogs! 🐶'
    shell: bash
  - name: Favorite book
    run: '.github/actions/my-composite-gh/book.sh'
    shell: bash
