name: Caller workflow
on: [workflow_dispatch]
jobs:
    use-reusable-workflow:
        uses: ./.github/workflows/called-workflow.yml
        with:
            who-to-greet: 'Johnny'
        secrets:
            token: ${{ secrets.MY_SECRET }}
            
