name: "Github actions demo"
on: push
jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Triggered event
              run: |
                echo "Triggered by event: ${{github.event_name }} 😎"
            - name: Runner
              run: |
                echo "Job is running in ${{runner.os}} 🐧 "  
            