name: Opened Issue
on:
  issues:
    types: labeled
jobs:
    run_if_label_present:
      if: github.event.label.name == 'hello' 
      runs-on: ubuntu-latest
      steps:
        - name: "Comment about changes we can't accept"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ISSUE: ${{ github.event.issue.html_url }}
          run: |
            gh issue comment "${{ github.event.issue.number }}" --body 'Hello diogobytes.'
