name: Playground
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      NAME: "Hello Diogo"
    steps:
      - name: greeting name
        run: |
          echo $NAME
        env:
          NAME: "Hello Joao"