name: Playground
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: check if contains
        if: contains('Hello World','llo')
        run: echo "Hello world "
          