name: Conditional env variable
on: 
  workflow_dispatch:
    inputs:
      day-of-the-week:
        description: "Which day is today?"
        default: "Sunday"
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check day of the week
        if: ${{ inputs.day-of-the-week == 'Monday'}}
        run: |
          echo "Today is ${{inputs.day-of-the-week}}"
